export default [
  {
    id: 341235,
    title: "Scent of a woman",
    rating: 2,
    poster: "placeholder url",
  },
  {
    id: 384522,
    title: "The usual suspects",
    rating: 4,
    poster: "placeholder url",
  },
  {
    id: 111234,
    title: "Encanto",
    rating: 5,
    poster: "placeholder url",
  },
  {
    id: 222222,
    title: "Återstoden av dagen",
    rating: 2,
    poster: "placeholder url",
  },
  {
    id: 911834,
    title: "Blue Jasmine",
    rating: 1,
    poster: "placeholder url",
  },
  {
    id: 457812,
    title: "Sayonara jim",
    rating: 3,
    poster: "placeholder url",
  },
  {
    id: 906423,
    title: "Polisskolan 3",
    rating: 5,
    poster: "placeholder url",
  },
  {
    id: 781199,
    title: "Gremlins 2",
    rating: 3,
    poster: "placeholder url",
  },
  {
    id: 346288,
    title: "High Fidelity",
    rating: 2,
    poster: "placeholder url",
  },
  {
    id: 445567,
    title: "Tenacious D",
    rating: 3,
    poster: "placeholder url",
  },
  {
    id: 556744,
    title: "Gomorrah",
    rating: 5,
    poster: "placeholder url",
  },
  {
    id: 231160,
    title: "Life of Brian",
    rating: 4,
    poster: "placeholder url",
  },
  {
    id: 669322,
    title: "Johnny Mnemonic",
    rating: 1,
    poster: "placeholder url",
  },
];
